What is Numpy? NumPy (Numerical Python) is a powerful Python library used for numerical computing and data manipulation. It provides a fast and efficient way to work with arrays, matrices, and mathematical operations.

In [1]:
#pip install ipykernel in command prompt
#pip install numpy in command prompt
#save file as .ipynb in vscode and select the kernel in current project folder

import numpy as np

In [2]:
np.__version__

'2.5.0'

In [3]:
#1. creating arrays
list1 = [1,2,3]
list1

[1, 2, 3]

In [ ]:
arr_list1 = np.array(list1) # creating array using list
arr_list1

array([1, 2, 3])

In [7]:
print(arr_list1)

[1 2 3]

In [ ]:
type(arr_list1)  # check data type of variable

numpy.ndarray

In [10]:
arr_list1.ndim  # check dimension of array

1

In [12]:
# creating 2-dim array using 2 lists
list1 = [1,2,3]
list2 = [4,5,6]
arr_list_1_2 = np.array([list1,list2])
print(arr_list_1_2)

[[1 2 3]
 [4 5 6]]

In [14]:
arr_list_1_2.ndim

2

In [18]:
# creating 3-dim array using 3 lists
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list_1_2_3 = np.array([[list1,list2,list3]])
print(arr_list_1_2_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

In [19]:
arr_list_1_2_3.ndim

3

NumPy uses a single data type (homogeneous data) mainly for speed and memory efficiency.
When all elements have the same type, NumPy knows exactly how much memory each element occupies and how to process it.

In [32]:

arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.dtype)

[1 2 3 4]
int64

In [ ]:
arr = np.array([1, 2.5, 3])
print(arr) #NumPy automatically upcasts elements to a common type that can represent all values.
print(arr.dtype) #The integers are converted to floats.

[1.  2.5 3. ]
float64

In [30]:
arr = np.array([1, 'hello', 3])
print(arr) #All elements become strings.
print(arr.dtype)

['1' 'hello' '3']
<U21

In [31]:

#NumPy can store different types? Yes, using the object dtype:
arr = np.array([1, 'hello', 3.5], dtype=object)
print(arr)
print(arr.dtype)

[1 'hello' 3.5]
object

In [ ]:
#2. numpy array attributes
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]

In [35]:
# Attributes of Array (properties of array)
print("shape - ",arr1.shape)  # share= rows, columns and height of array
print("size - ",arr1.size)  # number of elements in array
print("dType - ",arr1.dtype) # data type of elements in array
print("n_dim - ",arr1.ndim)  # dimension of array

shape -  (3,)
size -  3
dType -  int64
n_dim -  1

In [36]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]

In [37]:
print("shape - ",arr2.shape)  # share= rows, columns and height of array
print("size - ",arr2.size)  # number of elements in array
print("dType - ",arr2.dtype) # data type of elements in array
print("n_dim - ",arr2.ndim)  # dimension of array

shape -  (2, 3)
size -  6
dType -  int64
n_dim -  2

In [38]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]

In [39]:
print("shape - ",arr3.shape)  # share= rows, columns and height of array
print("size - ",arr3.size)  # number of elements in array
print("dType - ",arr3.dtype) # data type of elements in array
print("n_dim - ",arr3.ndim)  # dimension of array

shape -  (1, 3, 3)
size -  9
dType -  int64
n_dim -  3

In [41]:
#pip install pandas
import pandas as pd
pd.DataFrame(arr1)

   0
0  1
1  2
2  3

In [42]:
pd.DataFrame(arr2)

   0  1  2
0  1  2  3
1  4  5  6

In [45]:
#pd.DataFrame(arr3) #. Pandas is inherently 2-dimensional, so it cannot directly represent a true NumPy 3D array as a single DataFrame.

In [ ]:
#3. Array initialization methods
# zeros array : all elements are 0 shape:(rows,columns)
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]

In [ ]:
# ones array : all elements are 1 shape:(rows,columns)
ones_arr = np.ones((3,4))
print(ones_arr)
ones_arr.ndim

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

2

In [58]:
# Full array : all elements are same based on given value
full_arr = np.full((3,2),9)
print(full_arr)

[[9 9]
 [9 9]
 [9 9]]

In [ ]:
# Identity Matrix : diagonal elements are ones and all other elements are zeros and will be in square shape
id_arr = np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [62]:
# empty array -  allocates memory but does not initialize the elements
print(np.empty(2))
# output (values are garbage/uninitialized):

[inf inf]

In [ ]:
# evenly spaced array : elements are evenly spaced based on step value  (start,stop,step)
print(np.arange(1,10,1)) #stop is exclusive #start is inclusive
print(np.arange(1,10,2))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]

In [66]:
# specific number of equally spaced values between a range : elements are equally spaced based on step value
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]

In [ ]:
# random values array - float - shape: (rows,columns)
print(np.random.rand(3,2))

[[0.31231024 0.04201341]
 [0.69109265 0.37763318]
 [0.58934825 0.50914609]]

In [ ]:
# random values array - int - (start, stop,(rows,columns))
print(np.random.randint(10,20,(4,4)))

[[11 18 12 16]
 [15 17 19 13]
 [16 15 12 19]
 [19 11 13 19]]

In [ ]:
#4. Array Indexing and Slicing
# Indexing on 1 Dimensional Array
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]

In [120]:
pd.DataFrame(a)

   0
0  1
1  3
2  5
3  7
4  9

In [75]:
print(a[0])  #accessing elements through indexes #positive index

1

In [76]:
print(a[-2]) #negative index

7

In [ ]:
# Slicing :
# array[start index:stop index:step] - step is by default positive 1 
# stop - exclusive and start - inclusive
# forward step is positive and backward step is negative
print(a[0:3]) # First 3 elements #positive step

[1 3 5]

In [78]:
print(a[-3:]) # last 3 elements #positive step

[5 7 9]

In [ ]:
print(a[1:4]) # middle 3 elements #positive step

[3 5 7]

In [82]:
print(a[0::2]) # All alternative elements with steps

[1 5 9]

In [ ]:
print(a[::])

[1 3 5 7 9]

In [ ]:
# 2D Array: [rows, columns]                   # 2D Array takes 2 values - rows and columns for indexing
# 3D Array: [layers/height, rows, columns]    # 3D Array takes 3 values - height, rows and columns for indexing

# 2D Array: [rows, columns] 
# array[row_index, column_index] is equivalent to array[row_index][column_index]

# 3D Array: [layers, rows, columns]
# array[layer_index, row_index, column_index] is equivalent to array[layer_index][row_index][column_index]

In [ ]:
# Indexing on 2 Dimensional Array
a2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(a2)
print(a2.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2

In [119]:
pd.DataFrame(a2)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
print(a2[0]) # 1st row values 
print(a2[1]) # 2nd row values 
print(a2[2]) # 3rd row values

[1 2 3]
[4 5 6]
[7 8 9]

In [ ]:
print(a2[:,0]) # 1st col values (row index-slicing to take all rows,column index)
print(a2[:,1]) # 2nd col values (row index-slicing to take all rows,column index)
print(a2[:,2]) # 3rd col values (row index-slicing to take all rows,column index)

[1 4 7]
[2 5 8]
[3 6 9]

In [117]:
print(a2[0][1])
print(a2[1][1])

2
5

In [ ]:
# Slicing on 2D array
print(a2[0])  # specific element - 1D
print(a2[1:]) # slicing part - 2D

[1 2 3]
[[4 5 6]
 [7 8 9]]

In [ ]:
print(a2[::1,0]) # 1st col values (row index-slicing to take all rows with step ,column index)
print(a2[::2,1]) # 2nd col values (row index-slicing to take all rows with step ,column index)
print(a2[::2,2]) # 3rd col values (row index-slicing to take all rows with step ,column index)

[1 4 7]
[2 8]
[3 9]

In [127]:
print(a2[::,0:2]) #slicing on columns(row index-slicing to take all rows,column index-slicing to 2 columns)

[[1 2]
 [4 5]
 [7 8]]

In [126]:
print(a2[::,1:2]) #slicing on columns(row index-slicing to take all rows,column index-slicing to 1 column)

[[2]
 [5]
 [8]]

In [129]:
print(a2[1::,1:2]) #slicing on columns(row index-slicing to take 2 rows,column index-slicing to 1 column)

[[5]
 [8]]

In [130]:
print(a2[2::,1:2]) #slicing on columns(row index-slicing to take 1 row,column index-slicing to 1 column)

[[8]]

In [131]:
#5. Array Reshaping and Flattening
# Reshape Array: changing its dimensions (e.g., rows and columns) without altering the actual data
# Flatten Array: transforming a multi-dimensional array into a single-dimensional array

In [138]:
a1 = np.array([1,2,3,4,5])
print(a1)
a1.ndim

[1 2 3 4 5]

1

In [134]:
pd.DataFrame(a1)

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:
reshaped = a1.reshape(5,1)   #shape: (rows,columns) # re-shaped array from (1,5) to (5,1) and dimension 1 changes to dimension 2
print(reshaped)
reshaped.ndim

[[1]
 [2]
 [3]
 [4]
 [5]]

2

In [141]:
pd.DataFrame(reshaped)

   0
0  1
1  2
2  3
3  4
4  5

In [142]:
a1 = np.array([1,2,3,4,5,6])
print(a1)
a1.ndim

[1 2 3 4 5 6]

1

In [ ]:
reshaped2 = a1.reshape(2,3)   #shape: (rows,columns) # re-shaped array from (1,6) to (2,3) and dimension 1 changes to dimension 2
print(reshaped2)
reshaped2.ndim

[[1 2 3]
 [4 5 6]]

2

In [144]:
pd.DataFrame(reshaped2)

   0  1  2
0  1  2  3
1  4  5  6

In [145]:
print(reshaped2.flatten())

[1 2 3 4 5 6]

In [ ]:
#6 Array Stacking and Splitting
# Array Stacking:  combining multiple arrays along a new axis, resulting in an array with a higher dimension than the input arrays
# Array Splitting: means dividing a array into multiple smaller arrays along a specified axis.

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b))) # vertical stacking - row wise          -> output array is 2D

[[1 2 3]
 [4 5 6]]

In [ ]:
print(np.hstack((a,b)))   # horizontal stacking - column wise     -> output array is 1D

[1 2 3 4 5 6]

In [148]:
vstack = np.vstack((a,b))
print(pd.DataFrame(vstack))

   0  1  2
0  1  2  3
1  4  5  6

In [150]:
hstack = np.hstack((a,b))
print(pd.DataFrame(hstack))

   0
0  1
1  2
2  3
3  4
4  5
5  6

In [151]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]

In [ ]:
print(np.hsplit(c,3)) # horizontal split into 3 parts -> input and output array are same dimension

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]

In [155]:
hsplit = np.hsplit(c,3) #The output will be a list of three 2D  arrays

for arr in hsplit:
    print(arr)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]

In [159]:
for arr in hsplit:
    print(pd.DataFrame(arr))

   0
0  1
1  4
   0
0  2
1  5
   0
0  3
1  6

In [157]:
print(np.vsplit(c,2)) # vertical split -> input and output array are same dimension

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [158]:
vsplit = np.vsplit(c,2) #The output will be a list of two 2D  arrays

for arr in vsplit:
    print(arr)

[[1 2 3]]
[[4 5 6]]

In [160]:
vsplit = np.vsplit(c,2) 

for arr in vsplit:
    print(pd.DataFrame(arr))

   0  1  2
0  1  2  3
   0  1  2
0  4  5  6

In [161]:
#7. Mathematical Operations on Array
a = np.array([10,20,40,-30])
print(a)

[ 10  20  40 -30]

In [162]:
print(a+10) # add a value in array
print(a-30) # subs a value in array
print(a*2) # multiply by a value in array
print(a/10) # divide by a value in array

[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]

In [163]:
b = np.array([1,4,9])
print(b)

[1 4 9]

In [165]:
print(np.square(b))
print(np.sqrt(b))
print(np.sin(b))
print(np.cos(b))
print(np.tan(b))

[ 1 16 81]
[1. 2. 3.]
[ 0.84147098 -0.7568025   0.41211849]
[ 0.54030231 -0.65364362 -0.91113026]
[ 1.55740772  1.15782128 -0.45231566]

In [ ]:
# FYI: list vs Array
# one of the reason we array instead of list : time taken by an operation on list is more >>>>> than array
#%%time
numbers = list(range(1, 100000001))
result = [x+5 for x in numbers]
#CPU times: total: 6.86 s
#Wall time: 6.91 s

In [ ]:
#%%time
numbers = np.arange(1,100000001)
result = numbers+5
#CPU times: total: 2.19 s
#Wall time: 2.21 s

In [169]:
#8. Mathematical Operations on Muliple Arrays

In [ ]:
a =np.array([1,2,3])
b =np.array([4,5,6])

print(a)
print(b)

[1 2 3]
[4 5 6]

In [ ]:
print(np.add(a,b))  # add two arrays
print(np.subtract(a,b))  # subtract two arrays
print(np.multiply(a,b))  # multiply two arrays
print(np.divide(a,b))    # divide two arrays

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]

In [ ]:
# Dot product: computes the inner product of the two vectors and sum the results 1*4+2*5+3*6
print(np.dot(a,b)) # dot product

32

In [ ]:
print(a.T) # Transpose: Returns an array with axes transposed - rows to columns and columns to rows

[1 2 3]

In [ ]:
t = np.array([[1,2,3],[4,5,6]])
print(t)   # initial shape: 2,3
print(t.T) # shape after transpose: 3,2

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]

In [10]:
#9. Statistical Functions
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]

In [12]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6

In [13]:
#10. Array Comparison
a = np.array([1,5,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 5 3]
[4 5 6]

In [ ]:
print(a==b)  # comparing each elements of an array
print(np.array_equal(a,b))  # comparing complete array

[False  True False]
False

In [15]:
#11. Broadcasting
# Broadcasting: is a mechanism that allows arithmetic operations to be performed on arrays of different shapes and sizes,
# it eliminates the need for explicit loops or reshaping operations, making code more concise, readable and efficient.

# Broadcasting Rules:
    # Compare shapes from right to left.
    # Dimensions must match or be 1.
    # If one array has fewer dimensions, pad its shape on the left with 1s.
    # Any dimension equal to 1 can stretch to match the other array.

In [16]:
a = np.array([1,2,3,4])
b = np.array([5])
print(a+b)      # adding 1D with 0ne-element array to 1D with multi-element array

[6 7 8 9]

In [17]:
c = np.array([[1,2,3], [4,5,6]])
d = np.array([10,20,30])
print(c+d)      # adding 2D with 6-element array (2,3) to 1D with 6-element array

[[11 22 33]
 [14 25 36]]

In [19]:
#12. Handling with nan & inf
data1 = np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]

In [ ]:
print(np.isnan(data1)) # check null value and returns boolean value

[False False  True False False]

In [ ]:
print(np.nan_to_num(data1))  # replace non-finite values within an array with specified finite numbers

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]

In [22]:
#12. save and load arrays
arr = np.array([1,0,0,8])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 8]

In [23]:
load_arr = np.load('my_array.npy')
print(load_arr)

[1 0 0 8]